;; CWA-2026-006 trigger - CosmWasm ABI contract (generated by gen.py).
;; Do not hand-edit; edit gen.py and regenerate.
(module
  (import "env" "db_read" (func $db_read (param i32) (result i32)))
  (memory (export "memory") 1)
  (global $heap (mut i32) (i32.const 8192))

  ;; bump allocator: returns a pointer to a Region{offset,capacity,length}
  (func (export "allocate") (param $size i32) (result i32)
    (local $data i32)
    (local $region i32)
    (local.set $data (global.get $heap))
    (global.set $heap
      (i32.and
        (i32.add (i32.add (local.get $data) (local.get $size)) (i32.const 7))
        (i32.const -8)))
    (local.set $region (global.get $heap))
    (global.set $heap (i32.add (global.get $heap) (i32.const 16)))
    (i32.store (local.get $region) (local.get $data))
    (i32.store offset=4 (local.get $region) (local.get $size))
    (i32.store offset=8 (local.get $region) (i32.const 0))
    (local.get $region))

  (func (export "deallocate") (param $ptr i32))
  (func (export "interface_version_8"))

  ;; static regions + data
  (data (i32.const 0) "\01\00\00\00")
  (data (i32.const 16) "\30\00\00\00\01\00\00\00\01\00\00\00")
  (data (i32.const 32) "\00\01\00\00\40\00\00\00\3e\00\00\00")
  (data (i32.const 48) "\00")
  (data (i32.const 256) "\7b\22\6f\6b\22\3a\7b\22\6d\65\73\73\61\67\65\73\22\3a\5b\5d\2c\22\64\61\74\61\22\3a\6e\75\6c\6c\2c\22\61\74\74\72\69\62\75\74\65\73\22\3a\5b\5d\2c\22\65\76\65\6e\74\73\22\3a\5b\5d\7d\7d")

  (func $respond (result i32) (i32.const 32))

  (func (export "instantiate") (param i32 i32 i32) (result i32)
    (call $respond))

  (func (export "execute") (param i32 i32 i32) (result i32)
    (local $i i32)
    (block $exit
      (loop $l
        ;; live computed values -> register pressure
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        (i64.extend_i32_u (local.get $i))
        ;; condition (nonzero) -> then branch
        (i32.load (i32.const 0))
        ;; result-bearing if; the then-result is memory-backed
        (if (result i64)
          (then
            (i64.add (i64.extend_i32_u (local.get $i)) (i64.const 0x12345678)))
          (else
            (i64.extend_i32_u (local.get $i))))
        drop
        ;; release the live values
        drop drop drop drop drop drop drop drop drop drop drop drop drop drop drop drop
        ;; host-import call (real CosmWasm import, valid 1-byte key)
        (call $db_read (i32.const 16))
        drop
        ;; loop control
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br_if $l (i32.lt_u (local.get $i) (i32.const 300000)))
      )
    )
    (call $respond))
)
