;; E1 write-stream detector (generated by gen_writestream.py).
(module
  (import "env" "probe" (func $host (param i32 i32 i32) (result i32)))
  (memory 1)
  (data (i32.const 0) "\01\00\00\00")
  (func (export "run") (param $iters i32) (result i32)
    (local $i i32)
    (block $exit
      (loop $l
        ;; live computed values (i << 32) | K, K = 0..15
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 0))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 1))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 2))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 3))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 4))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 5))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 6))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 7))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 8))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 9))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 10))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 11))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 12))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 13))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 14))
        (i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) (i64.const 15))
        ;; condition (nonzero) -> then branch
        (i32.load (i32.const 0))
        (if (result i64)
          (then
            (i64.add (i64.extend_i32_u (local.get $i)) (i64.const 0x12345678)))
          (else
            (i64.extend_i32_u (local.get $i))))
        drop
        ;; host call while the live values are still allocated:
        ;; push_used_gpr writes them at the (drifted) rsp
        (call $host (local.get $i) (i32.const 0) (i32.const 0))
        drop
        ;; release the live values
        drop drop drop drop drop drop drop drop drop drop drop drop drop drop drop drop
        ;; loop control
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br_if $l (i32.lt_u (local.get $i) (local.get $iters)))
      )
    )
    (local.get $i)
  )
)
